# Generated by Django 3.1.1 on 2020-11-11 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product_product_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product',
            new_name='pppp',
        ),
    ]
